credentials:
  usernames:
    admin:
      email: admin@site.com
      name: admin
      password: $2b$12$yOZS2Ic/CuCdcMLh49yiD.OBuXPYWMN7TSuz/ifN38jAsh68faF0i
    # test:
    #   email: test@site.com
    #   name: test
    #   password: test    # get hashed password from generate_keys.py
cookie:
  expiry_days: 30
  key: oubi-UkN0Bq5jZlx8Ek3U1PeX9IsAhJV_FPYDy8sjkE=
  name: Sanalyze
preauthorized:
  emails:
    - admin@site.com
